# Generated by Django 4.2.25 on 2025-10-24 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: 2023-2024', max_length=20, unique=True, verbose_name='O‘quv yili nomi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol yil')),
            ],
            options={
                'verbose_name': 'O‘quv yili',
                'verbose_name_plural': 'O‘quv yillari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Shartnoma raqami')),
                ('contract_date', models.DateField(default=datetime.date.today, verbose_name='Shartnoma sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Shartnoma summasi')),
                ('grant_type', models.CharField(choices=[('none', 'Imtiyoz yo‘q'), ('CR', "Rag'batlantirish-CR (50%)"), ('MT', "Rag'batlantirish-Ma'naviyat (30%)"), ('IH', 'Ijtimoiy himoya')], default='none', max_length=10, verbose_name='Ichki grant turi')),
                ('grant_date', models.DateField(blank=True, null=True, verbose_name='Ichki grant sanasi')),
                ('grant_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grant foizi (%)')),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Grant summasi (so‘m)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='students.academicyear', verbose_name='O‘quv yili')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Davlat nomi')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tuman nomi')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Buyruq turi')),
            ],
            options={
                'verbose_name': 'Buyruq turi',
                'verbose_name_plural': 'Buyruq turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Viloyat nomi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.country', verbose_name='Davlat')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Yo'nalish kodi")),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('student_hemis_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Talaba ID')),
                ('course_year', models.PositiveSmallIntegerField(choices=[(1, '1-kurs'), (2, '2-kurs'), (3, '3-kurs'), (4, '4-kurs'), (5, '5-kurs')], default=1, verbose_name='Kursi')),
                ('education_type', models.CharField(choices=[('grant', 'Davlat granti'), ('contract', 'To‘lov-kontrakt')], default='contract', max_length=10, verbose_name="To'lov shakli")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name="Tug'ilgan joyi (matn)")),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami 2')),
                ('address', models.TextField(verbose_name="Yashash manzili (ko'cha, uy)")),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Millati')),
                ('passport_series_number', models.CharField(max_length=20, unique=True, verbose_name='Pasport SR')),
                ('personal_pin', models.CharField(max_length=14, unique=True, verbose_name='JShShIR')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Kim tomonidan berilgan')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Berilgan sanasi')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('status', models.CharField(choices=[('active', "O'qiydi"), ('academic', "Akademik ta'tilda"), ('expelled', 'Chetlashtirilgan'), ('graduated', 'Bitirgan')], default='active', max_length=20, verbose_name='Statusi')),
                ('education_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], max_length=20, verbose_name="Ta'lim shakli")),
                ('current_semester', models.PositiveSmallIntegerField(choices=[(1, '1-semestr'), (2, '2-semestr'), (3, '3-semestr'), (4, '4-semestr'), (5, '5-semestr'), (6, '6-semestr'), (7, '7-semestr'), (8, '8-semestr'), (9, '9-semestr'), (10, '10-semestr')], default=1, verbose_name='Semestr')),
                ('entry_score', models.FloatField(blank=True, null=True, verbose_name="To'plagan bali")),
                ('document', models.CharField(blank=True, choices=[('bor', 'Bor'), ('yoq', 'Yo‘q'), ('chala', 'Chala')], max_length=10, null=True, verbose_name='Hujjat holati')),
                ('document_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dokument haqida')),
                ('previous_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ta'lim olgan muassasasi")),
                ('document_type', models.CharField(blank=True, choices=[('shahodatnoma', 'Shahodatnoma'), ('diplom', 'Diplom')], max_length=20, null=True, verbose_name='Hujjat turi')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hujjat raqami')),
                ('previous_graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Tamomlagan yili')),
                ('certificate_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sertifikat')),
                ('transferred_from_university', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ko'chirgan OTM")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_citizenship', to='students.country', verbose_name='Fuqaroligi')),
                ('district', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.district', verbose_name='Tumani')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.group', verbose_name='Guruh')),
                ('previous_education_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_previous_country', to='students.country', verbose_name='Davlati')),
                ('previous_education_region', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='previous_education_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_previous_region', to='students.region', verbose_name='Viloyati')),
                ('region', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='citizenship', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_region', to='students.region', verbose_name='Viloyati')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.contract', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='Buyruq raqami')),
                ('order_date', models.DateField(verbose_name='Buyruq sanasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('tsch_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='TSCH sababi')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Ariza sanasi')),
                ('document_taken_date', models.DateField(blank=True, null=True, verbose_name='Hujjat olib ketilgan sanasi')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.ordertype', verbose_name='Buyruq turi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Buyruq',
                'verbose_name_plural': 'Buyruqlar',
                'ordering': ['-order_date'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.specialty', verbose_name="Yo'nalishi"),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.region', verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Talaba'),
        ),
        migrations.CreateModel(
            name='SubjectDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1-semestr'), (2, '2-semestr'), (3, '3-semestr'), (4, '4-semestr'), (5, '5-semestr'), (6, '6-semestr'), (7, '7-semestr'), (8, '8-semestr'), (9, '9-semestr'), (10, '10-semestr')], default=1, verbose_name='Semestr')),
                ('year_credit', models.PositiveSmallIntegerField(default=0, verbose_name='O‘quv yili umumiy kreditlari')),
                ('credit', models.PositiveSmallIntegerField(default=0, verbose_name='Fan krediti')),
                ('debt_type', models.CharField(choices=[('du', 'DU fandan qarzdorlik'), ('perevod', 'Perevod fandan qarzdorlik')], max_length=10, verbose_name='Qarzdorlik turi')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Qarzdorlik summasi (so‘m)')),
                ('status', models.CharField(choices=[('yopildi', 'Yopildi'), ('yopilmadi', 'Yopilmadi')], default='yopilmadi', max_length=10, verbose_name='Holati')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.academicyear', verbose_name='O‘quv yili')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Talaba')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Fan bo‘yicha qarzdorlik',
                'verbose_name_plural': 'Fanlar bo‘yicha qarzdorliklar',
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='PerevodRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='1 kredit uchun to‘lov (Perevod)')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear', verbose_name='O‘quv yili')),
            ],
            options={
                'verbose_name': 'Perevod stavkasi',
                'verbose_name_plural': 'Perevod stavkalari',
                'ordering': ['-year'],
                'unique_together': {('year',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('student', 'academic_year')},
        ),
    ]
