# Generated by Django 4.2.25 on 2025-10-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Yo'nalish kodi"),
        ),
    ]
