# Generated by Django 4.2.25 on 2025-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_specialty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_type',
            field=models.CharField(choices=[('grant', 'Davlat granti'), ('contract', 'To‘lov-shartnoma')], default='contract', max_length=10, verbose_name="To'lov shakli"),
        ),
    ]
