# Generated by Django 4.2.25 on 2025-10-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education_type',
            field=models.CharField(choices=[('grant', 'Davlat granti'), ('contract', 'To‘lov-shartnoma')], default='contract', max_length=20, verbose_name="To'lov shakli"),
        ),
    ]
