# Generated by Django 4.2.25 on 2025-10-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami 2'),
        ),
    ]
