# Generated by Django 4.2.25 on 2025-11-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('modul', 'Kredit-modul'), ('contract', "To'lov-shartnoma")], default='contract', max_length=10, verbose_name="To'lov maqsadi"),
        ),
    ]
