# Generated by Django 4.2.25 on 2025-11-06 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_contract_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdebt',
            name='amount_summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="To'lov summasi"),
        ),
        migrations.AddField(
            model_name='subjectdebt',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.contract', verbose_name='Shartnoma'),
        ),
        migrations.AddField(
            model_name='subjectdebt',
            name='payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="To'lov sanasi"),
        ),
    ]
