# Generated by Django 4.2.25 on 2025-12-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_subjectdebt_amount_summ_subjectdebt_contract_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
    ]
