# Generated by Django 4.2.25 on 2025-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_contract_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Fan nomi'),
        ),
    ]
