# Generated by Django 4.2.25 on 2025-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tsch_by_whom',
            field=models.CharField(choices=[('du', 'Diplomat University'), ('student', 'Talaba'), ('expelled', 'Chetlashtirilgan'), ('graduated', 'Bitirgan')], default='du', max_length=20, verbose_name='TSCH kim tomonidan'),
        ),
    ]
