# Generated by Django 4.2.25 on 2025-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_order_tsch_by_whom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tsch_by_whom',
            field=models.CharField(blank=True, choices=[('du', 'Diplomat University'), ('student', 'Talaba')], default='du', max_length=20, null=True, verbose_name='TSCH kim tomonidan'),
        ),
    ]
