# Generated by Django 4.2.25 on 2025-12-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_order_tsch_by_whom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hisobot',
            fields=[
            ],
            options={
                'verbose_name': 'Hisobotlar',
                'verbose_name_plural': '2. Hisobotlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.student',),
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Talaba', 'verbose_name_plural': '1. Talabalar'},
        ),
    ]
