# Generated by Django 4.2.25 on 2025-12-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_contract_grant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='grant_type',
            field=models.CharField(choices=[('none', 'Imtiyoz yo‘q'), ('CR', "Rag'batlantirish-CR (50%)"), ('MT', "Rag'batlantirish-Ma'naviyat (30%)"), ('QH', 'Qurbon Hayiti'), ('QB', 'Qabul'), ('IH', 'Ijtimoiy himoya')], default='none', max_length=10, verbose_name='Ichki grant turi'),
        ),
    ]
