# Generated by Django 4.2.25 on 2025-12-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_contract_grant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.PositiveSmallIntegerField(choices=[(1, '1-kurs'), (2, '2-kurs'), (3, '3-kurs'), (4, '4-kurs'), (5, '5-kurs')], verbose_name='Kurs')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1-semestr'), (2, '2-semestr'), (3, '3-semestr'), (4, '4-semestr'), (5, '5-semestr'), (6, '6-semestr'), (7, '7-semestr'), (8, '8-semestr'), (9, '9-semestr'), (10, '10-semestr')], default=1, verbose_name='Semestr')),
                ('education_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], max_length=20, verbose_name="Ta'lim shakli")),
                ('status', models.CharField(choices=[('active', "O'qiydi"), ('academic', "Akademik ta'tilda"), ('expelled', 'Chetlashtirilgan'), ('graduated', 'Bitirgan')], max_length=20, verbose_name='Statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear', verbose_name='O‘quv yili')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Talaba tarixi (Arxiv)',
                'verbose_name_plural': 'Talaba tarixi (Arxiv)',
                'ordering': ['-academic_year', 'student__full_name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
