# Generated by Django 4.2.25 on 2025-12-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_studenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthistory',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='status',
        ),
    ]
