# Generated by Django 4.2.25 on 2026-01-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_studenthistory_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='grant_type',
            field=models.CharField(choices=[('none', 'Imtiyoz yo‘q'), ('CR', 'Iqtidorli talabalar (25%)'), ('MT', 'Faol talabalar (15%)'), ('QH', 'Qurbon Hayiti'), ('QB', 'Qabul'), ('XM', 'Xodimlar'), ('IH', 'Ijtimoiy himoya')], default='none', max_length=10, verbose_name='Ichki grant turi'),
        ),
        migrations.CreateModel(
            name='SubjectRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kontrakt narxi')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.specialty', verbose_name="Yo'nalish")),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear', verbose_name='O‘quv yili')),
            ],
            options={
                'verbose_name': 'Fan stavkasi',
                'verbose_name_plural': 'Fan stavkalari',
                'ordering': ['-year'],
                'unique_together': {('year', 'specialty')},
            },
        ),
    ]
