# Generated by Django 4.2.25 on 2026-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_contract_grant_type_subjectrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectrate',
            name='education_form',
            field=models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], default='kunduzgi', max_length=20, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterUniqueTogether(
            name='subjectrate',
            unique_together={('year', 'specialty', 'education_form')},
        ),
    ]
