# Generated by Django 4.2.25 on 2026-03-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kadrlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oklad')),
                ('allowance_percent', models.DecimalField(decimal_places=2, default=0, help_text='Masalan: 20', max_digits=5, verbose_name='Nadbavka (%)')),
                ('job_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Shtat birligi')),
                ('vacation_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otpusknoy')),
                ('annual_base_load', models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='Yillik asosiy yuklama')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_salary', to='kadrlar.teacher', verbose_name="O'qituvchi (Asosiy)")),
            ],
            options={
                'verbose_name': 'Asosiy stavka',
                'verbose_name_plural': 'Asosiy stavkalar',
            },
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='1 soat uchun haq')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rate', to='kadrlar.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Soatbay stavka',
                'verbose_name_plural': 'Soatbay stavkalar',
            },
        ),
    ]
