# Generated by Django 4.2.25 on 2026-03-13 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('kadrlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki')], default='kunduzgi', max_length=20, verbose_name="Ta'lim shakli")),
                ('course', models.IntegerField(choices=[(1, '1-kurs'), (2, '2-kurs'), (3, '3-kurs'), (4, '4-kurs'), (5, '5-kurs')], default=1, verbose_name='Kurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear', verbose_name="O'quv yili")),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.specialty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "O'quv reja",
                'verbose_name_plural': "O'quv rejalar",
                'ordering': ['-academic_year', 'specialty', 'course'],
            },
        ),
        migrations.CreateModel(
            name='PlanSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('majburiy', 'Majburiy'), ('tanlov', 'Tanlov')], default='majburiy', max_length=20, verbose_name='Fan turi')),
                ('credit', models.PositiveSmallIntegerField(default=4, verbose_name='Kredit')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1-semestr'), (2, '2-semestr'), (3, '3-semestr'), (4, '4-semestr'), (5, '5-semestr'), (6, '6-semestr'), (7, '7-semestr'), (8, '8-semestr'), (9, '9-semestr'), (10, '10-semestr')], verbose_name='Semestr')),
                ('semester_time', models.PositiveIntegerField(default=4, help_text='Masalan: 4 soat (Auditoriya soati / 15 hafta)', verbose_name='Haftalik soat')),
                ('total_hours', models.PositiveIntegerField(blank=True, help_text='Avtomatik hisoblanadi (Kredit * 30)', null=True, verbose_name='Umumiy soat')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza")),
                ('practice_hours', models.PositiveIntegerField(default=0, verbose_name='Amaliyot')),
                ('lab_hours', models.PositiveIntegerField(default=0, verbose_name='Laboratoriya')),
                ('seminar_hours', models.PositiveIntegerField(default=0, verbose_name='Seminar')),
                ('independent_hours', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Mustaqil ta'lim")),
                ('alternative_subjects', models.ManyToManyField(blank=True, help_text="Ushbu asosiy fan o'rniga qanday muqobil tanlovlar borligini ko'rsating (agar bo'lsa).", related_name='alternative_in_plans', to='students.subject', verbose_name='Muqobil (Tanlov) fanlar')),
                ('education_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.educationplan', verbose_name="O'quv reja")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Rejadagi fan',
                'verbose_name_plural': 'Rejadagi fanlar',
                'ordering': ['semester', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Xona raqami/nomi')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Sig'imi")),
                ('room_type', models.CharField(choices=[('lecture', "Ma'ruza zali"), ('practice', 'Amaliyot xonasi'), ('lab', 'Laboratoriya'), ('computer', 'Kompyuter xonasi'), ('sport', 'Sport zal')], default='practice', max_length=20, verbose_name='Xona turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Auditoriya',
                'verbose_name_plural': 'Auditoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Masalan: Ma'ruza-1 (Iqtisodiyot)", max_length=255, verbose_name='Nomi')),
                ('employment_type', models.CharField(choices=[('permanent', 'Asosiy (Shtat)'), ('hourly', 'Soatbay'), ('internal_part_time', "Ichki o'rindosh"), ('external_part_time', "Tashqi o'rindosh")], help_text="Ushbu dars o'qituvchining qaysi yuklamasiga yozilishini tanlang.", max_length=20, verbose_name='Yuklama turi')),
                ('lesson_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('practice', 'Amaliyot'), ('seminar', 'Seminar'), ('lab', 'Laboratoriya')], max_length=20, verbose_name='Dars turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='streams', to='students.group', verbose_name='Guruhlar')),
            ],
            options={
                'verbose_name': 'Patok',
                'verbose_name_plural': 'Patok',
                'ordering': ['lesson_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(help_text='Tanlangan rejalarga mos guruhlarni tanlang.', to='students.group', verbose_name='Guruhlar')),
                ('plan_subjects', models.ManyToManyField(help_text="Ushbu fan bo'yicha bir yoki bir nechta rejalarni tanlang (Masalan: Iqtisodiyot va Moliya).", to='education.plansubject', verbose_name='Rejadagi fanlar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Yuklama hajmi',
                'verbose_name_plural': 'Yuklamalar hajmi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('autumn', 'Kuzgi (Toq semestrlar)'), ('spring', 'Bahorgi (Juft semestrlar)')], default='autumn', max_length=10)),
                ('education_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi')], default='kunduzgi', max_length=20, verbose_name="Ta'lim shakli")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.room', verbose_name='Xona')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.teacher')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.timeslot')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.weekday')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['weekday', 'timeslot'],
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kichik guruh nomi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='students.group', verbose_name='Asosiy guruh')),
            ],
            options={
                'verbose_name': 'Kichik guruh',
                'verbose_name_plural': 'Kichik guruhlar',
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='sub_groups',
            field=models.ManyToManyField(blank=True, related_name='streams', to='education.subgroup', verbose_name='Kichik guruhlar'),
        ),
        migrations.AddField(
            model_name='stream',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadrlar.teacher', verbose_name="O'qituvchi"),
        ),
        migrations.AddField(
            model_name='stream',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='education.workload', verbose_name='Yuklama (Workload)'),
        ),
        migrations.CreateModel(
            name='SessionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('autumn', 'Kuzgi (Toq semestrlar)'), ('spring', 'Bahorgi (Juft semestrlar)')], default='autumn', max_length=10, verbose_name='Mavsum')),
                ('education_form', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi')], default='kunduzgi', max_length=20, verbose_name="Ta'lim shakli")),
                ('course', models.IntegerField(choices=[(1, '1-kurs'), (2, '2-kurs'), (3, '3-kurs'), (4, '4-kurs'), (5, '5-kurs')], verbose_name='Kurs')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('weeks_count', models.PositiveIntegerField(help_text='Kunduzgi: 12-15, Sirtqi: 3-4', verbose_name='Hafta soni')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear', verbose_name="O'quv yili")),
            ],
            options={
                'verbose_name': 'Sessiya davri',
                'verbose_name_plural': 'Sessiya davrlari',
                'ordering': ['academic_year', 'semester', 'education_form', 'course'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('reason', models.TextField(help_text="Nega joylashmadi? (Masalan: O'qituvchi band)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.workload')),
            ],
        ),
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('hours', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Soat miqdori (Moliya uchun)')),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Asosiy (Shtat)'), ('hourly', 'Soatbay'), ('internal_part_time', "Ichki o'rindosh"), ('external_part_time', "Tashqi o'rindosh")], help_text="O'qituvchining ushbu darsni o'tgan paytdagi ish turi. Stream dan avtomatik olinadi.", max_length=20, null=True, verbose_name='Ish turi (Moliya uchun)')),
                ('lesson_type', models.CharField(blank=True, choices=[('lecture', "Ma'ruza"), ('practice', 'Amaliyot'), ('seminar', 'Seminar'), ('lab', 'Laboratoriya')], help_text="Ma'ruza, Amaliyot, Seminar yoki Laboratoriya. Stream dan avtomatik olinadi.", max_length=20, null=True, verbose_name='Dars turi')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('held', "O'tildi (Tasdiqlandi)"), ('canceled', "Dars bo'lmadi"), ('replaced', 'Zamena (Almashtirildi)')], default='scheduled', max_length=20, verbose_name='Holati')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu (Izoh)')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name="O'quv bo'limi tasdiqladi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_lessons', to='kadrlar.teacher', verbose_name="Amalda o'tgan o'qituvchi")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.group', verbose_name='Guruh')),
                ('planned_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_lessons', to='kadrlar.teacher', verbose_name="Rejadagi o'qituvchi")),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.room', verbose_name='Xona')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Fan')),
                ('timetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='education.timetable', verbose_name='Jadval asosi')),
            ],
            options={
                'verbose_name': 'Kunlik Dars Qaydi (Jurnal)',
                'verbose_name_plural': 'Kunlik Darslar Jurnali',
                'ordering': ['-date', 'timetable__timeslot'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('academic_year', 'education_form', 'weekday', 'timeslot', 'teacher'), name='unique_teacher_slot_v2'),
        ),
        migrations.AlterUniqueTogether(
            name='subgroup',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionperiod',
            unique_together={('academic_year', 'semester', 'education_form', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='plansubject',
            unique_together={('education_plan', 'subject', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonlog',
            unique_together={('timetable', 'date', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='educationplan',
            unique_together={('specialty', 'academic_year', 'education_form', 'course')},
        ),
    ]
