# Generated by Django 4.2.25 on 2026-03-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tartib raqami')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('head_manager', models.ForeignKey(blank=True, help_text="Ushbu tuzilmani (kafedra yoki bo'limni) boshqaradigan user", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL, verbose_name="Kafedra yoki Bo'lim Rahbari")),
            ],
            options={
                'verbose_name': "Kafedra / Bo'lim",
                'verbose_name_plural': "Kafedralar / Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=120, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='Otasining ismi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jinsi')),
                ('passport_info', models.CharField(help_text='Masalan: AA1234567', max_length=20, unique=True, verbose_name='Passport Seriya va Raqam')),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='JSHShIR / Passport')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kadrlar/photos/', verbose_name='Rasm')),
                ('scientific_degree', models.CharField(blank=True, choices=[('none', "Yo'q"), ('phd', 'PhD'), ('dsc', 'DSc')], default='none', max_length=10, verbose_name='Ilmiy daraja')),
                ('scientific_title', models.CharField(blank=True, choices=[('none', "Yo'q"), ('docent', 'Dotsent'), ('professor', 'Professor'), ('academic', 'Akademik')], default='none', max_length=20, verbose_name='Ilmiy unvon')),
                ('is_teacher', models.BooleanField(default=False, verbose_name="O'qituvchi")),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Ishga qabul qilingan sana')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('dismissed', "Ishdan bo'shatilgan")], default='pending', max_length=20, verbose_name='Holat')),
                ('approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan (HR)')),
                ('archived', models.BooleanField(default=False, verbose_name='Arxivlangan (soft)')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kadrlar.department', verbose_name="Kafedra/Bo'lim")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar (HR)',
                'ordering': ['department__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Asosiy Tashkiliy Tuzilma', max_length=255, verbose_name='Tuzilma nomi')),
                ('xml_data', models.TextField(blank=True, help_text='Bu yerga tegmang, diagramma avtomatik saqlanadi.', verbose_name='Diagramma kodi (XML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tashkiliy Tuzilma',
                'verbose_name_plural': 'Tashkiliy Tuzilma',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Lavozim nomi')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Quiz nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type_permanent', models.BooleanField(default=False, verbose_name='Doimiy (Shtat)')),
                ('work_type_hourly', models.BooleanField(default=False, verbose_name='Soatbay')),
                ('work_type_internal_part_time', models.BooleanField(default=False, verbose_name="Ichki o'rindosh")),
                ('work_type_external_part_time', models.BooleanField(default=False, verbose_name="Tashqi o'rindosh")),
                ('schedule_approved', models.BooleanField(default=False, help_text="O'qituvchining fanlari va bo'sh vaqtlari O'quv bo'limi tomonidan tekshirib tasdiqlanganda belgilanadi.", verbose_name="Jadval va Yuklama tasdiqlandi (O'quv bo'limi)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='kadrlar.employee', verbose_name="Xodim (O'qituvchi)")),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='students.subject', verbose_name='Dars beradigan fanlari')),
            ],
            options={
                'verbose_name': "O'qituvchi profili",
                'verbose_name_plural': "O'qituvchilar (O'quv bo'limi)",
                'permissions': [('can_approve_schedule', "Jadvalni tasdiqlay oladi (O'quv bo'limi)")],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True, verbose_name='Para #')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vaqt bloki (Para)',
                'verbose_name_plural': 'Vaqt bloklari',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kun nomi')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Hafta kuni',
                'verbose_name_plural': 'Hafta kunlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SimpleStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Rektor, Buxgalteriya', max_length=255, verbose_name='Tugun nomi')),
                ('children_layout', models.CharField(choices=[('horizontal', 'Gorizontal (Yonma-yon)'), ('vertical', 'Vertikal (Ustma-ust)')], default='horizontal', help_text="Ushbu tugunning ichidagi bo'limlar qanday ko'rinsin? (Masalan: Prorektorlar qatori uchun 'Gorizontal', Bo'limlar ro'yxati uchun 'Vertikal')", max_length=20, verbose_name='Joylashuv')),
                ('node_type', models.CharField(choices=[('normal', 'Markazdan'), ('staff_left', 'Chapdan joylashtirish'), ('staff_right', "O'ngdan joylashtirish")], default='normal', help_text="Agar bu bo'lim asosiy shoxdan chetda (chap yoki o'ngda) tursa, mosini tanlang.", max_length=20, verbose_name='Tugun turi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ko'rinish tartibi")),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadrlar.department', verbose_name="Bo'lim (Butun jamoani chiqarish)")),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadrlar.employee', verbose_name='Aniq xodim (Yakka tartibda)')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kadrlar.simplestructure', verbose_name='Yuqori tugun')),
            ],
            options={
                'verbose_name': 'Tuzilma Elementi',
                'verbose_name_plural': 'Tashkiliy Tuzilma (Sozlamalar)',
            },
        ),
        migrations.CreateModel(
            name='QuizScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Masalan: Xavfsizlikka ehtiyoj, Ijtimoiy ehtiyoj', max_length=200, verbose_name='Kategoriya nomi')),
                ('related_questions', models.CharField(blank=True, help_text='Qaysi savollar ushbu kategoriyani baholaydi? (Masalan: 1, 5, 9, 13)', max_length=200, verbose_name='Tegishli savollar')),
                ('min_score', models.IntegerField(default=0, verbose_name='Min. Ball')),
                ('max_score', models.IntegerField(default=25, verbose_name='Max. Ball')),
                ('conclusion', models.TextField(help_text="Agar to'plangan ball shu oraliqda bo'lsa, chiqadigan matn.", verbose_name='Xulosa / Tavsif')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Baholash Mezoni',
                'verbose_name_plural': 'Baholash Mezonlari (Tahlil)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizScoringInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(default=0, verbose_name='Min. Ball')),
                ('max_score', models.IntegerField(default=25, verbose_name='Max. Ball')),
                ('conclusion', models.TextField(help_text="Agar to'plangan ball shu oraliqda bo'lsa, chiqadigan matn.", verbose_name='Xulosa / Tavsif')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_info', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Baholash Mezoni izohi',
                'verbose_name_plural': 'Baholash Mezoni izohi',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResultKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Ha', 'Ha'), ("Yo'q", "Yo'q")], default='A', max_length=10, verbose_name='Variant')),
                ('description', models.TextField(help_text="Ushbu tip haqida to'liq ma'lumot", verbose_name='Tavsif')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_keys', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Natija Kaliti',
                'verbose_name_plural': 'Natija Kalitlari',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struct', models.JSONField(verbose_name='Batafsil natijalar')),
                ('total_score', models.IntegerField(default=0, verbose_name='Umumiy ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.employee')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib raqami')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Javob matni')),
                ('symbol', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Ha', 'Ha'), ("Yo'q", "Yo'q")], default='A', max_length=10, verbose_name='Variant')),
                ('score', models.IntegerField(default=0, help_text='Ushbu javob tanlansa beriladigan ball', verbose_name='Ball')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kadrlar.quizquestion')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text="Xodim bir vaqtning o'zida bir nechta lavozimda ishlashi mumkin", related_name='employees', to='kadrlar.position', verbose_name='Lavozimlar'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('reference', "Ma'lumotnoma"), ('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('other', 'Boshqa')], max_length=50, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='kadrlar/documents/', verbose_name='Fayl')),
                ('number', models.CharField(blank=True, max_length=200, verbose_name='Hujjat raqami')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kadrlar.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='ArchivedEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Arxivdagi xodim',
                'verbose_name_plural': "Arxiv (Bo'shaganlar)",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kadrlar.employee',),
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='kadrlar.teacher')),
                ('timeslots', models.ManyToManyField(blank=True, to='kadrlar.timeslot', verbose_name="Bo'sh vaqtlar (Paralar)")),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.weekday', verbose_name='Hafta kuni')),
            ],
            options={
                'verbose_name': "Bo'sh vaqt",
                'verbose_name_plural': "O'qituvchi vaqtlari",
                'ordering': ['weekday__order'],
                'unique_together': {('teacher', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='QuizPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ruxsat berilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_permissions', to='kadrlar.employee')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Testga ruxsat',
                'verbose_name_plural': 'Testga ruxsatlar',
                'unique_together': {('quiz', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Buyruq raqami')),
                ('order_type', models.CharField(choices=[('hire', 'Qabul qilish'), ('dismiss', 'Ishdan bo‘shatish'), ('transfer', 'Ko‘chirish')], max_length=20, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('document', models.FileField(blank=True, null=True, upload_to='kadrlar/orders/', verbose_name='Buyruq fayli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='kadrlar.employee')),
            ],
            options={
                'verbose_name': 'Buyruq',
                'verbose_name_plural': 'Buyruqlar',
                'unique_together': {('employee', 'number')},
            },
        ),
    ]
