# Generated by Django 4.2.25 on 2025-12-18 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Kafedra / Bo'lim",
                'verbose_name_plural': "Kafedralar / Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=120, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='Otasining ismi')),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='JSHShIR / Passport')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kadrlar/photos/', verbose_name='Rasm')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Lavozim')),
                ('is_teacher', models.BooleanField(default=False, verbose_name="O'qituvchi")),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Ishga qabul qilingan sana')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('dismissed', "Ishdan bo'shatilgan")], default='pending', max_length=20, verbose_name='Holat')),
                ('approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan (HR)')),
                ('archived', models.BooleanField(default=False, verbose_name='Arxivlangan (soft)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='kadrlar.department', verbose_name="Kafedra/Bo'lim")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('obyektivka', 'Obyektivka'), ('diplom', 'Diplom'), ('certificate', 'Sertifikat'), ('other', 'Boshqa')], max_length=50, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='kadrlar/documents/', verbose_name='Fayl')),
                ('number', models.CharField(blank=True, max_length=200, verbose_name='Hujjat raqami')),
                ('issued_by', models.CharField(blank=True, max_length=255, verbose_name='Kim tomonidan berilgan')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Berilgan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Amal qilish muddati (agar bo'lsa)")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kadrlar.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Buyruq raqami')),
                ('order_type', models.CharField(choices=[('hire', 'Qabul qilish'), ('dismiss', 'Ishdan bo‘shatish'), ('transfer', 'Ko‘chirish')], max_length=20, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('document', models.FileField(blank=True, null=True, upload_to='kadrlar/orders/', verbose_name='Hujjat (skan)')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='kadrlar.employee')),
            ],
            options={
                'verbose_name': 'Buyruq',
                'verbose_name_plural': 'Buyruqlar',
                'ordering': ['-date'],
                'unique_together': {('employee', 'number')},
            },
        ),
    ]
