# Generated by Django 4.2.25 on 2025-12-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
