# Generated by Django 4.2.25 on 2026-03-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees2', to='kadrlar.department', verbose_name="Qo'shimcha Kafedra/Bo'lim"),
        ),
    ]
