# Generated by Django 4.2.25 on 2025-12-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0017_remove_studenthistory_semester_and_more'),
        ('kadrlar', '0002_remove_document_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True, verbose_name='Para #')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vaqt bloki (Para)',
                'verbose_name_plural': 'Vaqt bloklari',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kun nomi')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Hafta kuni',
                'verbose_name_plural': 'Hafta kunlari',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Hujjat', 'verbose_name_plural': 'Hujjatlar'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar (HR)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyruq', 'verbose_name_plural': 'Buyruqlar'},
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('diplom', 'Diplom'), ('certificate', 'Sertifikat'), ('other', 'Boshqa')], max_length=50, verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='kadrlar/orders/', verbose_name='Buyruq fayli'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_teach_lecture', models.BooleanField(default=True, verbose_name="Ma'ruza o'ta oladimi?")),
                ('can_teach_practice', models.BooleanField(default=True, verbose_name="Amaliyot o'ta oladimi?")),
                ('schedule_approved', models.BooleanField(default=False, help_text="O'qituvchining fanlari va bo'sh vaqtlari O'quv bo'limi tomonidan tekshirib tasdiqlanganda belgilanadi.", verbose_name="Jadval va Yuklama tasdiqlandi (O'quv bo'limi)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='kadrlar.employee', verbose_name="Xodim (O'qituvchi)")),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='students.subject', verbose_name='Dars beradigan fanlari')),
            ],
            options={
                'verbose_name': "O'qituvchi profili",
                'verbose_name_plural': "O'qituvchilar (O'quv bo'limi)",
                'permissions': [('can_approve_schedule', "Jadvalni tasdiqlay oladi (O'quv bo'limi)")],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='kadrlar.teacher')),
                ('timeslots', models.ManyToManyField(blank=True, to='kadrlar.timeslot', verbose_name="Bo'sh vaqtlar (Paralar)")),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.weekday', verbose_name='Hafta kuni')),
            ],
            options={
                'verbose_name': "Bo'sh vaqt",
                'verbose_name_plural': "O'qituvchi vaqtlari",
                'ordering': ['weekday__order'],
                'unique_together': {('teacher', 'weekday')},
            },
        ),
    ]
