# Generated by Django 4.2.25 on 2025-12-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0004_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('reference', "Ma'lumotnoma"), ('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('other', 'Boshqa')], max_length=50, verbose_name='Hujjat turi'),
        ),
    ]
