# Generated by Django 4.2.25 on 2025-12-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kadrlar', '0005_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_manager',
            field=models.ForeignKey(blank=True, help_text='Ushbu kafedrani boshqaradigan user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL, verbose_name='Kafedra Mudiri'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
