# Generated by Django 4.2.25 on 2025-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0006_department_head_manager_alter_department_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='can_teach_lab',
            field=models.BooleanField(default=True, verbose_name="Laboratoriya o'ta oladimi?"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='can_teach_seminar',
            field=models.BooleanField(default=True, verbose_name="Seminar o'ta oladimi?"),
        ),
    ]
