# Generated by Django 4.2.25 on 2025-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0007_teacher_can_teach_lab_teacher_can_teach_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_info',
            field=models.CharField(blank=True, help_text='Masalan: AA1234567', max_length=20, verbose_name='Passport Seriya va Raqam'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('reference', "Ma'lumotnoma"), ('diploma', 'Diplom'), ('certificate', 'Sertifikat'), ('other', 'Boshqa')], max_length=50, verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='can_teach_lab',
            field=models.BooleanField(default=False, verbose_name="Laboratoriya o'ta oladimi?"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='can_teach_lecture',
            field=models.BooleanField(default=False, verbose_name="Ma'ruza o'ta oladimi?"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='can_teach_practice',
            field=models.BooleanField(default=False, verbose_name="Amaliyot o'ta oladimi?"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='can_teach_seminar',
            field=models.BooleanField(default=False, verbose_name="Seminar o'ta oladimi?"),
        ),
    ]
