# Generated by Django 4.2.25 on 2025-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0008_employee_passport_info_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passport_info',
            field=models.CharField(help_text='Masalan: AA1234567', max_length=20, unique=True, verbose_name='Passport Seriya va Raqam'),
        ),
    ]
