# Generated by Django 4.2.25 on 2026-01-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0010_alter_department_head_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_type_hourly',
            field=models.BooleanField(default=False, verbose_name='Soatbay'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_type_permanent',
            field=models.BooleanField(default=False, verbose_name='Doimiy (Shtat)'),
        ),
    ]
