# Generated by Django 4.2.25 on 2026-01-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0011_teacher_work_type_hourly_teacher_work_type_permanent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Test / So'rovnoma",
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('category', models.CharField(blank=True, help_text="Maslow uchun: 'Xavfsizlik', 'Ijtimoiy', 'Hurmat', 'O'zini namoyon qilish'", max_length=100, null=True, verbose_name='Kategoriya')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kadrlar.assessment')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Variant (A, B, C...)')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Variant matni')),
                ('score', models.IntegerField(default=0, verbose_name='Bal')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kadrlar.assessmentquestion')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Natija xulosasi')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.assessment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='kadrlar.employee')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Xodimlar Natijalari',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.questionoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.assessmentquestion')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kadrlar.employeeresult')),
            ],
            options={
                'unique_together': {('result', 'question')},
            },
        ),
    ]
