# Generated by Django 4.2.25 on 2026-01-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0012_assessment_assessmentquestion_questionoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='assessment',
        ),
        migrations.AlterUniqueTogether(
            name='employeeanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='option',
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='result',
        ),
        migrations.RemoveField(
            model_name='employeeresult',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='employeeresult',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='EmployeeAnswer',
        ),
        migrations.DeleteModel(
            name='EmployeeResult',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
