# Generated by Django 4.2.25 on 2026-01-08 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0013_remove_assessmentquestion_assessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='kadrlar.test')),
            ],
            options={
                'verbose_name': 'Test Kategoriyasi',
                'verbose_name_plural': 'Test Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib raqami')),
                ('category', models.ForeignKey(blank=True, help_text="Agar bu savol ma'lum bir ko'rsatkichni aniqlasa, o'shani tanlang.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='kadrlar.testcategory', verbose_name='Kategoriya (Maslow uchun ustun)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kadrlar.test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('total_score', models.IntegerField(default=0, verbose_name='Umumiy ball')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='kadrlar.employee')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.test')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Variant matni')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kadrlar.question')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='EmployeeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='kadrlar.employeetestresult')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.answeroption')),
            ],
            options={
                'unique_together': {('result', 'question')},
            },
        ),
    ]
