# Generated by Django 4.2.25 on 2026-01-08 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0014_test_testcategory_question_employeetestresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Quiz nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizlar',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Javob varianti')),
                ('score', models.IntegerField(default=0, help_text='Ushbu javob tanlansa beriladigan ball', verbose_name='Ball')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib raqami')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeeresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='employeeresponse',
            name='result',
        ),
        migrations.RemoveField(
            model_name='employeeresponse',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='employeetestresult',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeetestresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testcategory',
            name='test',
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='EmployeeResponse',
        ),
        migrations.DeleteModel(
            name='EmployeeTestResult',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kadrlar.quizquestion'),
        ),
    ]
