# Generated by Django 4.2.25 on 2026-01-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0015_quiz_quizanswer_quizquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='text',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Ha', 'Ha'), ("Yo'q", "Yo'q")], default='A', max_length=10, verbose_name='Variant'),
        ),
    ]
