# Generated by Django 4.2.25 on 2026-01-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0016_alter_quizanswer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResultKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Ha', 'Ha'), ("Yo'q", "Yo'q")], default='A', max_length=10, verbose_name='Variant')),
                ('title', models.CharField(help_text='Masalan: Dominance (Hukmronlik)', max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(help_text="Ushbu tip haqida to'liq ma'lumot", verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/keys/', verbose_name='Rasm (Icon)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_keys', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Natija Kaliti',
                'verbose_name_plural': 'Natija Kalitlari (DISC/Maslow)',
            },
        ),
    ]
