# Generated by Django 4.2.25 on 2026-01-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0017_quizresultkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='related_key',
            field=models.ForeignKey(blank=True, help_text="Ushbu javob tanlansa, qaysi ko'rsatkichga ball qo'shilsin? (Masalan: D ga)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='kadrlar.quizresultkey', verbose_name='Kalit (DISC)'),
        ),
        migrations.AlterField(
            model_name='quizresultkey',
            name='code',
            field=models.CharField(help_text='Masalan: D, I, S, C', max_length=50, verbose_name='Kod'),
        ),
    ]
