# Generated by Django 4.2.25 on 2026-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0018_quizanswer_related_key_alter_quizresultkey_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='related_key',
        ),
        migrations.AlterField(
            model_name='quizresultkey',
            name='code',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Ha', 'Ha'), ("Yo'q", "Yo'q")], default='A', max_length=10, verbose_name='Variant'),
        ),
    ]
