# Generated by Django 4.2.25 on 2026-01-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0019_remove_quizanswer_related_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresultkey',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quizresultkey',
            name='title',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='symbol',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Ha', 'Ha'), ("Yo'q", "Yo'q")], default='A', max_length=10, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='text',
            field=models.TextField(verbose_name='Javob matni'),
        ),
    ]
