# Generated by Django 4.2.25 on 2026-01-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0020_remove_quizresultkey_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresultkey',
            options={'verbose_name': 'Natija Kaliti', 'verbose_name_plural': 'Natija Kalitlari'},
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struct', models.JSONField(verbose_name='Batafsil natijalar')),
                ('total_score', models.IntegerField(default=0, verbose_name='Umumiy ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.employee')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
            },
        ),
        migrations.CreateModel(
            name='QuizPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ruxsat berilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_permissions', to='kadrlar.employee')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Testga ruxsat',
                'verbose_name_plural': 'Testga ruxsatlar',
                'unique_together': {('quiz', 'employee')},
            },
        ),
    ]
