# Generated by Django 4.2.25 on 2026-01-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0021_alter_quizresultkey_options_quizresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Masalan: Xavfsizlikka ehtiyoj, Ijtimoiy ehtiyoj', max_length=200, verbose_name='Kategoriya nomi')),
                ('related_questions', models.CharField(blank=True, help_text='Qaysi savollar ushbu kategoriyani baholaydi? (Masalan: 1, 5, 9, 13)', max_length=200, verbose_name='Tegishli savollar')),
                ('min_score', models.IntegerField(default=0, verbose_name='Min. Ball')),
                ('max_score', models.IntegerField(default=25, verbose_name='Max. Ball')),
                ('conclusion', models.TextField(help_text="Agar to'plangan ball shu oraliqda bo'lsa, chiqadigan matn.", verbose_name='Xulosa / Tavsif')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Baholash Mezoni',
                'verbose_name_plural': 'Baholash Mezonlari (Tahlil)',
                'ordering': ['category_name', '-min_score'],
            },
        ),
    ]
