# Generated by Django 4.2.25 on 2026-01-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0022_quizscoringrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizscoringrule',
            options={'ordering': ['id'], 'verbose_name': 'Baholash Mezoni', 'verbose_name_plural': 'Baholash Mezonlari (Tahlil)'},
        ),
        migrations.CreateModel(
            name='QuizScoringInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(default=0, verbose_name='Min. Ball')),
                ('max_score', models.IntegerField(default=25, verbose_name='Max. Ball')),
                ('conclusion', models.TextField(help_text="Agar to'plangan ball shu oraliqda bo'lsa, chiqadigan matn.", verbose_name='Xulosa / Tavsif')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_info', to='kadrlar.quiz')),
            ],
            options={
                'verbose_name': 'Baholash Mezoni izohi',
                'verbose_name_plural': 'Baholash Mezoni izohi',
                'ordering': ['id'],
            },
        ),
    ]
