# Generated by Django 4.2.25 on 2026-01-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0023_alter_quizscoringrule_options_quizscoringinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Arxivdagi xodim',
                'verbose_name_plural': "Arxiv (Bo'shaganlar)",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kadrlar.employee',),
        ),
    ]
