# Generated by Django 4.2.25 on 2026-01-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0025_alter_department_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department__order', 'order'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar (HR)'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tartib raqami'),
        ),
    ]
