# Generated by Django 4.2.25 on 2026-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0026_alter_employee_options_remove_department_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='scientific_degree',
            field=models.CharField(blank=True, choices=[('none', "Yo'q"), ('phd', 'PhD'), ('dsc', 'DSc')], default='none', max_length=10, verbose_name='Ilmiy daraja'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scientific_title',
            field=models.CharField(blank=True, choices=[('none', "Yo'q"), ('docent', 'Dotsent'), ('professor', 'Professor'), ('academic', 'Akademik')], default='none', max_length=20, verbose_name='Ilmiy unvon'),
        ),
    ]
