# Generated by Django 4.2.25 on 2026-01-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0027_teacher_scientific_degree_teacher_scientific_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Lavozim nomi')),
                ('order', models.PositiveIntegerField(default=0, help_text="Lavozimlar ro'yxatida chiqish tartibi", verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text="Xodim bir vaqtning o'zida bir nechta lavozimda ishlashi mumkin", related_name='employees', to='kadrlar.position', verbose_name='Lavozimlar'),
        ),
    ]
