# Generated by Django 4.2.25 on 2026-01-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0028_position_remove_employee_position_employee_positions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Lavozim', 'verbose_name_plural': 'Lavozimlar'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='order',
        ),
    ]
