# Generated by Django 4.2.25 on 2026-01-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0029_alter_position_options_remove_position_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='scientific_degree',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='scientific_title',
        ),
        migrations.AddField(
            model_name='employee',
            name='scientific_degree',
            field=models.CharField(blank=True, choices=[('none', "Yo'q"), ('phd', 'PhD (Falsafa doktori)'), ('dsc', 'DSc (Fan doktori)')], default='none', max_length=10, verbose_name='Ilmiy daraja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='scientific_title',
            field=models.CharField(blank=True, choices=[('none', "Yo'q"), ('docent', 'Dotsent'), ('professor', 'Professor'), ('academic', 'Akademik')], default='none', max_length=20, verbose_name='Ilmiy unvon'),
        ),
    ]
