# Generated by Django 4.2.25 on 2026-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0031_department_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Loyiha nomi')),
                ('data', models.JSONField(default=dict, verbose_name='Struktura JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
