# Generated by Django 4.2.25 on 2026-01-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0032_structuredraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructureDraft',
        ),
    ]
