# Generated by Django 4.2.25 on 2026-01-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0033_delete_structuredraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
    ]
