# Generated by Django 4.2.25 on 2026-01-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0034_remove_department_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='kadrlar.department', verbose_name='Yuqori turuvchi tuzilma'),
        ),
    ]
