# Generated by Django 4.2.25 on 2026-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0036_alter_department_head_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Struktura nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('chart_data', models.JSONField(blank=True, default=dict, verbose_name="Diagramma ma'lumotlari")),
                ('layout_type', models.CharField(choices=[('standard', 'Standart (Davlat)'), ('modern', 'Zamonaviy (Modern)'), ('horizontal', 'Gorizontal')], default='standard', max_length=20, verbose_name='Dizayn turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tashkiliy Struktura',
                'verbose_name_plural': 'Tashkiliy Strukturalar',
            },
        ),
    ]
