# Generated by Django 4.2.25 on 2026-01-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0037_structuremap'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Struktura nomi')),
                ('slug', models.SlugField(help_text='URL uchun unikal nom', unique=True)),
                ('template_style', models.CharField(choices=[('gov', 'Davlat standarti (Rasmiy)'), ('corporate', 'Korporativ (Modern)'), ('compact', 'Kompakt (Minimalizm)'), ('hierarchy', 'Ierarxiya (Daraxtsimon)')], default='gov', max_length=50, verbose_name='Dizayn Shabloni')),
                ('structure_data', models.JSONField(blank=True, default=dict, verbose_name="Struktura JSON ma'lumotlari")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tashkiliy Struktura',
                'verbose_name_plural': 'Tashkiliy Strukturalar',
            },
        ),
        migrations.DeleteModel(
            name='StructureMap',
        ),
    ]
