# Generated by Django 4.2.25 on 2026-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrlar', '0038_organizationstructure_delete_structuremap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstructure',
            name='template_style',
            field=models.CharField(choices=[('simple', 'Oddiy'), ('corporate', 'Korporativ (Modern)'), ('hierarchy', 'Ierarxiya (Daraxtsimon)')], default='gov', max_length=50, verbose_name='Dizayn Shabloni'),
        ),
    ]
